# Generated by Django 4.0.1 on 2022-02-15 21:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_avatar_profile_bio_profile_updated_and_more'),
        ('pollish', '0002_auto_20220114_0959'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='poll',
        #     unique_together=set(),
        # ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_image',
            field=models.ImageField(blank=True, upload_to='poll_directory_path'),
        ),
        migrations.AddField(
            model_name='poll',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='core.profile'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='poll',
            unique_together={('created', 'profile')},
        ),
        migrations.CreateModel(
            name='ChoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pollish.choice')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='poll',
            name='user',
        ),
    ]
