# Generated by Django 4.0.1 on 2022-02-19 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_bio'),
        ('pollish', '0009_alter_choice_choice_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='poll',
            unique_together={('profile', 'created_at')},
        ),
    ]
