# Generated by Django 4.0.1 on 2022-02-24 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pollish', '0010_alter_poll_options_rename_created_poll_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poll',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='choice',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
        migrations.AddField(
            model_name='choice',
            name='users',
            field=models.ManyToManyField(related_name='choices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='poll',
            unique_together={('user', 'created_at')},
        ),
        migrations.RemoveField(
            model_name='poll',
            name='profile',
        ),
    ]
