# Generated by Django 4.0.1 on 2022-02-25 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollish', '0013_remove_choice_choice_image_pollimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollimage',
            name='choice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='pollish.choice'),
        ),
    ]
