# Generated by Django 4.0.1 on 2022-02-25 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pollish', '0014_alter_pollimage_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='comment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='poll',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterUniqueTogether(
            name='pollimage',
            unique_together={('poll', 'choice')},
        ),
    ]
