# Generated by Django 4.0.1 on 2022-03-28 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollish', '0019_comment_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pollish.choice'),
        ),
    ]
