# Generated by Django 4.0.1 on 2022-03-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollish', '0020_alter_comment_choice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollimage',
            unique_together=set(),
        ),
    ]
