# Generated by Django 4.0.1 on 2022-04-24 06:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pollish', '0025_community_created_at_community_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
