# Generated by Django 4.0.1 on 2022-06-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollish', '0028_alter_choice_choice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='question_text',
            field=models.TextField(),
        ),
    ]
