# Generated by Django 4.0.1 on 2022-07-24 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollish', '0030_alter_community_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pollish.choice'),
        ),
        migrations.AlterField(
            model_name='pollimage',
            name='choice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pollish.choice'),
        ),
    ]
