# Generated by Django 3.2.8 on 2021-12-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(default='no_picture.png', upload_to='users')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
