# Generated by Django 4.0.1 on 2022-02-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
