# Generated by Django 3.2.8 on 2021-12-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='Option A', max_length=60),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question_text',
            field=models.CharField(default='', max_length=120),
        ),
    ]
