# Generated by Django 3.2.8 on 2021-12-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211228_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='question_text',
            field=models.CharField(default='Add your question here', max_length=120),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
