# Generated by Django 3.2.8 on 2021-12-29 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
        ('polls', '0005_alter_choice_poll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterField(
            model_name='poll',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='users.user'),
        ),
        migrations.AlterUniqueTogether(
            name='poll',
            unique_together={('user', 'created')},
        ),
    ]
